name: dj
channels:
  - conda-forge
dependencies:
  - autopep8
  - django=2.2.2
  - django-taggit=0.24.0
  - ipython
  - libpq
  - markdown=2.6.11
  - pillow=6.2.1
  - postgresql
  - postgresql-plpython
  - psycopg2
  - pylint
